const mutationsType = {
	GLOBAL_SHOW_MESSAGE: 'GLOBAL_SHOW_MESSAGE',
	GLOBAL_HIDE_MESSAGE: 'GLOBAL_HIDE_MESSAGE',
	GLOBAL_SET_USERINFO: 'GLOBAL_SET_USERINFO',
	GLOBAL_RESET_USERINFO: 'GLOBAL_RESET_USERINFO'
}

module.exports = mutationsType
